services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: olympics
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
  app:
    build: app
    depends_on:
      - db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: olympics
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    volumes:
      - app:/app
    tty: true
    command: bash
    networks:
      - app-network


volumes:
  db_data:
  app:
networks:
  app-network:
    driver: bridge

